name: SoSoValue ETF Flow (API)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,3,6,9 * * *"   # UTC 0/3/6/9 = JST 9/12/15/18

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore send state
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: sosovalue_state.json
          key: sosovalue-state-${{ github.run_id }}
          restore-keys: |
            sosovalue-state-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SoSoValue API Sentry
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SOSO_API_KEY: ${{ secrets.SOSO_API_KEY }}
          # 銘柄別API（設定すれば内訳を取得。未設定なら集計のみ）
          SOSO_FUNDS_API: ${{ secrets.SOSO_FUNDS_API }}
          SEND_ETH: "1"
          SHOW_TOP_N: "24"
          # 月上限（デフォ1000）を変えたいときだけ指定
          MAX_CALLS_PER_MONTH: "1000"
          FORCE_SEND: "1"     # ← これで aggregate を強制送信
        run: |
          set -euxo pipefail
          python -u sosovalue_api_etf_flow.py

      - name: Upload payload dump (if any)
        if: always() && hashFiles('last_payload.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: sosovalue-last-payload-${{ github.run_attempt }}
          path: last_payload.json

      - name: Save send state
        if: ${{ always() && hashFiles('sosovalue_state.json') != '' }}
        uses: actions/cache/save@v4
        with:
          path: sosovalue_state.json
          key: sosovalue-state-${{ github.run_id }}

      - name: Run cumulative chart (BTC+ETH)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SOSO_API_KEY: ${{ secrets.SOSO_API_KEY }}           # v1 デモ
          SOSO_CLIENT_ID: ${{ secrets.SOSO_CLIENT_ID }}       # v2 使うなら
          SOSO_CLIENT_SECRET: ${{ secrets.SOSO_CLIENT_SECRET }}
        run: |
          python -u sosovalue_etf_cum_chart.py

